version: '3'
services:
    app:
        build:
            context: .
            dockerfile: ./app.dockerfile
        # image: 'node:18'
        ports:
            - 3000:3000
        volumes:
            - ./app:/usr/app/
            - /usr/app/node_modules
        command: "npm start"

    # mariadb:
    #     image: mariadb:latest
    #     volumes:
    #         - ./db:/var/lib/mysql
    #     environment:
    #         TZ: "Asia/Manila"
    #         MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    #         MYSQL_ROOT_PASSWORD: "root"
    #         MYSQL_USER: 'mdbusr0'
    #         MYSQL_PASSWORD: 'mdbusr0'
#    adminer-dev:
#        image: adminer:latest
#        links:
#            - 'mariadb-dev:db'
#        ports:
#            - 81:8080

# volumes:
#     persist0: